version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout # check out the code in the project directory
      - run: sudo npm install -g npm@latest
      - run: npm install
  test:
    - run: *run_tests
  
workflows:  
  run-test:
    when:
      - equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - build
      - test:
          requires:
            - build
      
aliases:
  - &run_tests
    name: Running API tests
    command: npm run test
